vim.api.nvim_set_hl(0, '@ibl.scope.char.1', { fg = '' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'FloatBorder', { bg = '' })
vim.api.nvim_set_hl(0, 'ListishQfSign', { bg = '' })
vim.api.nvim_set_hl(0, 'MiniIndentscopeSymbol', { fg = '#ea6962' })

vim.api.nvim_set_hl(0, 'NeoTreeFloatTitle', { bg = '' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = '' })
vim.api.nvim_set_hl(0, 'NotificationInfo', { bg = '' })
vim.api.nvim_set_hl(0, 'Pmenu', { bg = '' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', { fg = '#ea6962' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', { fg = '#a9b665' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', { fg = '#d8a657' })

-- vim.api.nvim_set_hl(0, 'lualine_c_normal', { bg = '#14141a' })
-- vim.api.nvim_set_hl(0, 'lualine_b_inactive', { bg = '#14141a' })
-- vim.api.nvim_set_hl(0, 'lualine_c_normal', { bg = '#1e1e2e' })
-- vim.api.nvim_set_hl(0, 'lualine_b_inactive', { bg = '#1e1e2e' })
-- vim.api.nvim_set_hl(0, 'AvanteInlineHint', { fg = '#1e1e2e' })
