vim.keymap.set('n', '<C-a>', 'gg<S-v><S-g>', { silent = true })
vim.keymap.set('n', '<C-s>', ':w<CR>')
vim.keymap.set('n', '<C-w>down', '<C-w>j', { silent = true })
vim.keymap.set('n', '<C-w>left', '<C-w>h', { silent = true })
vim.keymap.set('n', '<C-w>right', '<C-w>l', { silent = true })
vim.keymap.set('n', '<C-w>up', '<C-w>k', { silent = true })
vim.keymap.set('n', '<M-,>', '<c-w>5<')
vim.keymap.set('n', '<M-.>', '<c-w>5>')
vim.keymap.set('n', '<M-/>', '<C-W>-')
vim.keymap.set('n', '<M-;>', '<C-W>+')
vim.keymap.set('n', '<S-Tab>', ':bNext<CR>', { silent = true })
vim.keymap.set('n', '<c-left>', ':bNext<CR>', { silent = true })
vim.keymap.set('n', '<c-right>', ':bnext<CR>', { silent = true })
vim.keymap.set('n', '<leader>bb', ':bd<CR>', { silent = true })
vim.keymap.set('n', '<leader>bd', ':bd<CR>', { silent = true })
vim.keymap.set('n', '<leader>cc', ':vsplit | term gcc % && a.exe<CR>i', { silent = true, desc = 'gcc compile and run' })
vim.keymap.set('n', '<leader>dd', ':DBUIToggle<CR>', { silent = true, desc = 'Open definition in vsplit' })
vim.keymap.set('n', '<leader>e', ':Neotree toggle float<CR>', { silent = true })
vim.keymap.set('n', '<leader>l1', ':set rnu nu<CR>')
vim.keymap.set('n', '<leader>l2', ':set nornu nonu<CR>')
vim.keymap.set('n', '<leader>l3', ':set nornu nu<CR>')
vim.keymap.set('n', '<leader>ll', ':vsplit | Telescope lsp_definitions<CR>', { silent = true, desc = 'Open definition in vsplit' })
vim.keymap.set('n', '<leader>n', ':NoiceAll<CR>', { silent = true, desc = 'Noice: for msgs' })
vim.keymap.set('n', '<leader>t', ':TroubleToggle<CR>')
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, { desc = 'Go to previous diagnostic message' })
vim.keymap.set('n', ']d', vim.diagnostic.goto_next, { desc = 'Go to next diagnostic message' })
vim.keymap.set('n', 'c', '"_c', { noremap = true })
vim.keymap.set('n', 'd', '"_d', { noremap = true })
vim.keymap.set('n', 'j', "v:count == 0 ? 'gj' : 'j'", { expr = true, silent = true })
vim.keymap.set('n', 'k', "v:count == 0 ? 'gk' : 'k'", { expr = true, silent = true })
vim.keymap.set('t', '<C-t>', '<C-\\><C-n>', { noremap = true, silent = true })
